package tenkupng.karuikey

import android.content.Context
import android.graphics.Paint
import java.util.Locale

internal data class EmojiEntry(
    val emoji: String,
    val name: String,
    val keywords: List<String> = emptyList(),
    val variants: List<String> = emptyList(),
    val localName: String = ""
)

internal enum class EmojiCategory(val titleRes: Int, val iconRes: Int) {
    RECENT(R.string.emoji_category_recent, R.drawable.ic_emoji_schedule),
    FACES(R.string.emoji_category_faces, R.drawable.ic_emoji_mood),
    PEOPLE(R.string.emoji_category_people, R.drawable.ic_emoji_emoji_people),
    ANIMALS(R.string.emoji_category_animals, R.drawable.ic_emoji_emoji_nature),
    FOOD(R.string.emoji_category_food, R.drawable.ic_emoji_fastfood),
    TRAVEL(R.string.emoji_category_travel, R.drawable.ic_emoji_directions_car),
    ACTIVITIES(R.string.emoji_category_activities, R.drawable.ic_emoji_sports_soccer),
    OBJECTS(R.string.emoji_category_objects, R.drawable.ic_emoji_lightbulb),
    SYMBOLS(R.string.emoji_category_symbols, R.drawable.ic_emoji_emoji_symbols),
    FLAGS(R.string.emoji_category_flags, R.drawable.ic_emoji_flag)
}

/** Unicode emoji with CLDR en/ru names, generated by tools/emoji/generate_emoji.py. */
internal object EmojiCatalog {
    private const val ASSET = "emoji/emoji.tsv"

    @Volatile
    private var data: Map<EmojiCategory, List<EmojiEntry>>? = null

    /** Loads the catalog once; safe to call from a background thread to warm it up. */
    fun load(context: Context): Map<EmojiCategory, List<EmojiEntry>> {
        data?.let { return it }
        synchronized(this) {
            data?.let { return it }
            val paint = Paint()
            val loaded = context.applicationContext.assets.open(ASSET).bufferedReader().useLines {
                parse(it) { emoji -> paint.hasGlyph(emoji) }
            }
            data = loaded
            return loaded
        }
    }

    /** Parses the generated TSV, keeping only emoji the device font can draw. */
    fun parse(lines: Sequence<String>, supports: (String) -> Boolean):
        Map<EmojiCategory, List<EmojiEntry>> {
        val result = LinkedHashMap<EmojiCategory, MutableList<EmojiEntry>>()
        for (line in lines) {
            if (line.isBlank()) continue
            val columns = line.split('\t')
            if (columns.size < 7) continue
            val category = runCatching { EmojiCategory.valueOf(columns[0]) }.getOrNull() ?: continue
            val emoji = columns[1]
            if (!supports(emoji)) continue
            val variants = columns[2].split(' ').filter { it.isNotEmpty() && supports(it) }
            val keywords = (columns[4].split('|') + columns[6].split('|')).filter { it.isNotEmpty() }
            result.getOrPut(category) { ArrayList() }
                .add(EmojiEntry(emoji, columns[3], keywords, variants, columns[5]))
        }
        return result
    }

    fun entries(category: EmojiCategory, context: Context): List<EmojiEntry> {
        if (category == EmojiCategory.RECENT) {
            val byEmoji = HashMap<String, EmojiEntry>()
            allEntries(context).forEach { entry ->
                byEmoji[entry.emoji] = entry
                entry.variants.forEach { byEmoji[it] = entry.copy(emoji = it, variants = emptyList()) }
            }
            return EmojiHistory.recent(context).mapNotNull { byEmoji[it] }
        }
        return load(context)[category].orEmpty()
    }

    fun search(query: String, context: Context): List<EmojiEntry> =
        rank(allEntries(context), query, EmojiHistory.counts(context))

    /**
     * Ranks matches for a query in English or Russian: exact name, a whole name word, a name
     * word prefix, a whole keyword, a keyword prefix, then any substring. Ties prefer emoji
     * the user picks more often, then shorter names, then Unicode order.
     */
    fun rank(entries: List<EmojiEntry>, query: String, usage: Map<String, Int>,
            limit: Int = Int.MAX_VALUE): List<EmojiEntry> {
        val wanted = query.trim().lowercase(Locale.ROOT)
        if (wanted.isEmpty()) return emptyList()
        val scored = ArrayList<Pair<EmojiEntry, Int>>()
        for (entry in entries) {
            val tier = tierOf(entry, wanted)
            if (tier < NO_MATCH) scored.add(entry to tier)
        }
        return scored.sortedWith(compareBy<Pair<EmojiEntry, Int>> { it.second }
            .thenByDescending { (entry, _) ->
                (usage[entry.emoji] ?: 0) + entry.variants.sumOf { usage[it] ?: 0 }
            }
            .thenBy { (entry, _) -> words(entry.name).size })
            .take(limit)
            .map { it.first }
    }

    private const val NO_MATCH = 6

    private fun tierOf(entry: EmojiEntry, wanted: String): Int {
        val names = listOf(entry.name, entry.localName).map { it.lowercase(Locale.ROOT) }
        if (names.any { it == wanted }) return 0
        val nameWords = names.flatMap(::words)
        if (nameWords.any { it == wanted }) return 1
        if (nameWords.any { it.startsWith(wanted) }) return 2
        val keywords = entry.keywords.map { it.lowercase(Locale.ROOT) }
        val keywordWords = keywords.flatMap(::words)
        if (keywordWords.any { it == wanted }) return 3
        if (keywordWords.any { it.startsWith(wanted) }) return 4
        if (names.any { it.contains(wanted) } || keywords.any { it.contains(wanted) }) return 5
        return NO_MATCH
    }

    private fun words(text: String) = text.split(' ', ':', ',', '-').filter { it.isNotEmpty() }

    fun allEntries(context: Context): List<EmojiEntry> = load(context).values.flatten()
}
