package tenkupng.karuikey

import android.content.Context
import android.graphics.Paint
import java.util.Locale

internal data class EmojiEntry(
    val emoji: String,
    val name: String,
    val keywords: List<String> = emptyList(),
    val variants: List<String> = emptyList()
)

internal enum class EmojiCategory(val title: String, val tab: String) {
    RECENT("Recent", "⟳"),
    FACES("Faces", "🙂"),
    PEOPLE("People", "🧑"),
    ANIMALS("Animals & nature", "🐻"),
    FOOD("Food", "🍔"),
    TRAVEL("Travel & places", "🚗"),
    ACTIVITIES("Activities", "⚽"),
    OBJECTS("Objects", "💡"),
    SYMBOLS("Symbols", "💟"),
    FLAGS("Flags", "🏳️")
}

/** Unicode emoji with CLDR en/ru names, generated by tools/emoji/generate_emoji.py. */
internal object EmojiCatalog {
    private const val ASSET = "emoji/emoji.tsv"

    @Volatile
    private var data: Map<EmojiCategory, List<EmojiEntry>>? = null

    /** Loads the catalog once; safe to call from a background thread to warm it up. */
    fun load(context: Context): Map<EmojiCategory, List<EmojiEntry>> {
        data?.let { return it }
        synchronized(this) {
            data?.let { return it }
            val paint = Paint()
            val loaded = context.applicationContext.assets.open(ASSET).bufferedReader().useLines {
                parse(it) { emoji -> paint.hasGlyph(emoji) }
            }
            data = loaded
            return loaded
        }
    }

    /** Parses the generated TSV, keeping only emoji the device font can draw. */
    fun parse(lines: Sequence<String>, supports: (String) -> Boolean):
        Map<EmojiCategory, List<EmojiEntry>> {
        val result = LinkedHashMap<EmojiCategory, MutableList<EmojiEntry>>()
        for (line in lines) {
            if (line.isBlank()) continue
            val columns = line.split('\t')
            if (columns.size < 7) continue
            val category = runCatching { EmojiCategory.valueOf(columns[0]) }.getOrNull() ?: continue
            val emoji = columns[1]
            if (!supports(emoji)) continue
            val variants = columns[2].split(' ').filter { it.isNotEmpty() && supports(it) }
            val keywords = buildList {
                add(columns[5])
                addAll(columns[4].split('|'))
                addAll(columns[6].split('|'))
            }.filter { it.isNotEmpty() }
            result.getOrPut(category) { ArrayList() }
                .add(EmojiEntry(emoji, columns[3], keywords, variants))
        }
        return result
    }

    fun entries(category: EmojiCategory, context: Context): List<EmojiEntry> {
        if (category == EmojiCategory.RECENT) {
            val byEmoji = HashMap<String, EmojiEntry>()
            allEntries(context).forEach { entry ->
                byEmoji[entry.emoji] = entry
                entry.variants.forEach { byEmoji[it] = entry.copy(emoji = it, variants = emptyList()) }
            }
            return EmojiHistory.recent(context).mapNotNull { byEmoji[it] }
        }
        return load(context)[category].orEmpty()
    }

    fun search(query: String, context: Context): List<EmojiEntry> {
        val wanted = query.trim().lowercase(Locale.ROOT)
        if (wanted.isEmpty()) return emptyList()
        return allEntries(context).filter { entry ->
            entry.name.lowercase(Locale.ROOT).contains(wanted) ||
                entry.keywords.any { keyword ->
                    keyword.lowercase(Locale.ROOT).split(' ').any { it.startsWith(wanted) }
                }
        }
    }

    fun allEntries(context: Context): List<EmojiEntry> = load(context).values.flatten()
}
